// Code generated by MockGen. DO NOT EDIT.
// Source: his_client.go
//
// Generated by this command:
//
//	mockgen -source=his_client.go -destination=./mocks/mock_his_client.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "agnos-backend/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIHisClient is a mock of IHisClient interface.
type MockIHisClient struct {
	ctrl     *gomock.Controller
	recorder *MockIHisClientMockRecorder
	isgomock struct{}
}

// MockIHisClientMockRecorder is the mock recorder for MockIHisClient.
type MockIHisClientMockRecorder struct {
	mock *MockIHisClient
}

// NewMockIHisClient creates a new mock instance.
func NewMockIHisClient(ctrl *gomock.Controller) *MockIHisClient {
	mock := &MockIHisClient{ctrl: ctrl}
	mock.recorder = &MockIHisClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIHisClient) EXPECT() *MockIHisClientMockRecorder {
	return m.recorder
}

// FetchPatient mocks base method.
func (m *MockIHisClient) FetchPatient(apiBase, id string) (*models.HISPatientResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchPatient", apiBase, id)
	ret0, _ := ret[0].(*models.HISPatientResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchPatient indicates an expected call of FetchPatient.
func (mr *MockIHisClientMockRecorder) FetchPatient(apiBase, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchPatient", reflect.TypeOf((*MockIHisClient)(nil).FetchPatient), apiBase, id)
}
