// Code generated by MockGen. DO NOT EDIT.
// Source: handlers.go
//
// Generated by this command:
//
//	mockgen -source=handlers.go -destination=./mocks/mock_handlers.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockIPatientHandler is a mock of IPatientHandler interface.
type MockIPatientHandler struct {
	ctrl     *gomock.Controller
	recorder *MockIPatientHandlerMockRecorder
	isgomock struct{}
}

// MockIPatientHandlerMockRecorder is the mock recorder for MockIPatientHandler.
type MockIPatientHandlerMockRecorder struct {
	mock *MockIPatientHandler
}

// NewMockIPatientHandler creates a new mock instance.
func NewMockIPatientHandler(ctrl *gomock.Controller) *MockIPatientHandler {
	mock := &MockIPatientHandler{ctrl: ctrl}
	mock.recorder = &MockIPatientHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPatientHandler) EXPECT() *MockIPatientHandlerMockRecorder {
	return m.recorder
}

// Search mocks base method.
func (m *MockIPatientHandler) Search(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Search", c)
}

// Search indicates an expected call of Search.
func (mr *MockIPatientHandlerMockRecorder) Search(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockIPatientHandler)(nil).Search), c)
}

// MockIStaffHandler is a mock of IStaffHandler interface.
type MockIStaffHandler struct {
	ctrl     *gomock.Controller
	recorder *MockIStaffHandlerMockRecorder
	isgomock struct{}
}

// MockIStaffHandlerMockRecorder is the mock recorder for MockIStaffHandler.
type MockIStaffHandlerMockRecorder struct {
	mock *MockIStaffHandler
}

// NewMockIStaffHandler creates a new mock instance.
func NewMockIStaffHandler(ctrl *gomock.Controller) *MockIStaffHandler {
	mock := &MockIStaffHandler{ctrl: ctrl}
	mock.recorder = &MockIStaffHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIStaffHandler) EXPECT() *MockIStaffHandlerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIStaffHandler) Create(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Create", c)
}

// Create indicates an expected call of Create.
func (mr *MockIStaffHandlerMockRecorder) Create(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIStaffHandler)(nil).Create), c)
}

// Login mocks base method.
func (m *MockIStaffHandler) Login(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Login", c)
}

// Login indicates an expected call of Login.
func (mr *MockIStaffHandlerMockRecorder) Login(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockIStaffHandler)(nil).Login), c)
}
