// Code generated by MockGen. DO NOT EDIT.
// Source: repositories.go
//
// Generated by this command:
//
//	mockgen -source=repositories.go -destination=./mocks/mock_repositories.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "agnos-backend/internal/models"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockIPatientRepository is a mock of IPatientRepository interface.
type MockIPatientRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIPatientRepositoryMockRecorder
	isgomock struct{}
}

// MockIPatientRepositoryMockRecorder is the mock recorder for MockIPatientRepository.
type MockIPatientRepositoryMockRecorder struct {
	mock *MockIPatientRepository
}

// NewMockIPatientRepository creates a new mock instance.
func NewMockIPatientRepository(ctrl *gomock.Controller) *MockIPatientRepository {
	mock := &MockIPatientRepository{ctrl: ctrl}
	mock.recorder = &MockIPatientRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPatientRepository) EXPECT() *MockIPatientRepositoryMockRecorder {
	return m.recorder
}

// Search mocks base method.
func (m *MockIPatientRepository) Search(hospitalID uuid.UUID, filter models.SearchRequest) ([]models.Patient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", hospitalID, filter)
	ret0, _ := ret[0].([]models.Patient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockIPatientRepositoryMockRecorder) Search(hospitalID, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockIPatientRepository)(nil).Search), hospitalID, filter)
}

// Upsert mocks base method.
func (m *MockIPatientRepository) Upsert(data models.Patient) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockIPatientRepositoryMockRecorder) Upsert(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockIPatientRepository)(nil).Upsert), data)
}

// MockIStaffRepository is a mock of IStaffRepository interface.
type MockIStaffRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIStaffRepositoryMockRecorder
	isgomock struct{}
}

// MockIStaffRepositoryMockRecorder is the mock recorder for MockIStaffRepository.
type MockIStaffRepositoryMockRecorder struct {
	mock *MockIStaffRepository
}

// NewMockIStaffRepository creates a new mock instance.
func NewMockIStaffRepository(ctrl *gomock.Controller) *MockIStaffRepository {
	mock := &MockIStaffRepository{ctrl: ctrl}
	mock.recorder = &MockIStaffRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIStaffRepository) EXPECT() *MockIStaffRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIStaffRepository) Create(staff *models.Staff) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", staff)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIStaffRepositoryMockRecorder) Create(staff any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIStaffRepository)(nil).Create), staff)
}

// FindByUsernameAndHospital mocks base method.
func (m *MockIStaffRepository) FindByUsernameAndHospital(username string, hospitalID uuid.UUID) (*models.Staff, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUsernameAndHospital", username, hospitalID)
	ret0, _ := ret[0].(*models.Staff)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUsernameAndHospital indicates an expected call of FindByUsernameAndHospital.
func (mr *MockIStaffRepositoryMockRecorder) FindByUsernameAndHospital(username, hospitalID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUsernameAndHospital", reflect.TypeOf((*MockIStaffRepository)(nil).FindByUsernameAndHospital), username, hospitalID)
}

// MockIHospitalRepository is a mock of IHospitalRepository interface.
type MockIHospitalRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIHospitalRepositoryMockRecorder
	isgomock struct{}
}

// MockIHospitalRepositoryMockRecorder is the mock recorder for MockIHospitalRepository.
type MockIHospitalRepositoryMockRecorder struct {
	mock *MockIHospitalRepository
}

// NewMockIHospitalRepository creates a new mock instance.
func NewMockIHospitalRepository(ctrl *gomock.Controller) *MockIHospitalRepository {
	mock := &MockIHospitalRepository{ctrl: ctrl}
	mock.recorder = &MockIHospitalRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIHospitalRepository) EXPECT() *MockIHospitalRepositoryMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockIHospitalRepository) FindByID(id uuid.UUID) (*models.Hospital, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*models.Hospital)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockIHospitalRepositoryMockRecorder) FindByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockIHospitalRepository)(nil).FindByID), id)
}

// FindByName mocks base method.
func (m *MockIHospitalRepository) FindByName(name string) (*models.Hospital, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", name)
	ret0, _ := ret[0].(*models.Hospital)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockIHospitalRepositoryMockRecorder) FindByName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockIHospitalRepository)(nil).FindByName), name)
}
