// Code generated by MockGen. DO NOT EDIT.
// Source: services.go
//
// Generated by this command:
//
//	mockgen -source=services.go -destination=./mocks/mock_services.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "agnos-backend/internal/models"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockIPatientService is a mock of IPatientService interface.
type MockIPatientService struct {
	ctrl     *gomock.Controller
	recorder *MockIPatientServiceMockRecorder
	isgomock struct{}
}

// MockIPatientServiceMockRecorder is the mock recorder for MockIPatientService.
type MockIPatientServiceMockRecorder struct {
	mock *MockIPatientService
}

// NewMockIPatientService creates a new mock instance.
func NewMockIPatientService(ctrl *gomock.Controller) *MockIPatientService {
	mock := &MockIPatientService{ctrl: ctrl}
	mock.recorder = &MockIPatientServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPatientService) EXPECT() *MockIPatientServiceMockRecorder {
	return m.recorder
}

// Search mocks base method.
func (m *MockIPatientService) Search(hospitalID uuid.UUID, filter models.SearchRequest) ([]models.Patient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", hospitalID, filter)
	ret0, _ := ret[0].([]models.Patient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockIPatientServiceMockRecorder) Search(hospitalID, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockIPatientService)(nil).Search), hospitalID, filter)
}

// MockIStaffService is a mock of IStaffService interface.
type MockIStaffService struct {
	ctrl     *gomock.Controller
	recorder *MockIStaffServiceMockRecorder
	isgomock struct{}
}

// MockIStaffServiceMockRecorder is the mock recorder for MockIStaffService.
type MockIStaffServiceMockRecorder struct {
	mock *MockIStaffService
}

// NewMockIStaffService creates a new mock instance.
func NewMockIStaffService(ctrl *gomock.Controller) *MockIStaffService {
	mock := &MockIStaffService{ctrl: ctrl}
	mock.recorder = &MockIStaffServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIStaffService) EXPECT() *MockIStaffServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIStaffService) Create(username, password, hospitalName string) (*models.Staff, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", username, password, hospitalName)
	ret0, _ := ret[0].(*models.Staff)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIStaffServiceMockRecorder) Create(username, password, hospitalName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIStaffService)(nil).Create), username, password, hospitalName)
}

// Login mocks base method.
func (m *MockIStaffService) Login(username, password, hospitalName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", username, password, hospitalName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockIStaffServiceMockRecorder) Login(username, password, hospitalName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockIStaffService)(nil).Login), username, password, hospitalName)
}
